{
  "scripts": [
    {
      "id": "VT2",
      "name": "Extra emote slots",
      "version": "1.0",
      "author": "grabis",
      "official": true,
      "status": "Updating",
      "description": "unlock extra emote slots without gamepass.",
      "tags": ["free", "hud", "misc"],
      "date_create": "18.02.2026",
      "date_update": "18.02.2026 20:30",
      "url": "https://pastebin.com/raw/cYJpMAK2"
    }
  ],
  "configs": [
    {
      "id": "VT4",
      "name": "My cfg :D",
      "version": "1.0",
      "author": "grabis",
      "official": true,
      "status": "Working",
      "description": "main cfg for vantality",
      "tags": ["test", "test", "test", "test", "test"],
      "date_create": "18.02.2026",
      "date_update": "18.02.2026 20:30", 
      "url": "https://pastebin.com/raw/cYJpMAK2"
    }
  ]
}